<?php

/**
 * @file
 * Install, update and uninstall functions for the SPHTechBlog installation profile.
 */

use Drupal\user\Entity\User;
use Drupal\user\RoleInterface;
use Drupal\shortcut\Entity\Shortcut;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function SPHTechBlog_install() {
  include_once DRUPAL_ROOT.'/core/profiles/standard/standard.install';
  standard_install();
}
